import Head from 'next/head'
import Image from 'next/image'
import '../styles/Home.module.css'

export default function Home() {
    return (
    <div className="container">
        <Head>
            <title>PixelTs</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
        </Head>

        <main className="storeMain">
            <div className="loginbox">
                <p className="loginTitle">Login</p>
                <hr/>
                <form>
                    <input id="loginUser" type="text" placeholder="Username..."></input>
                    <br/>
                    <br/>
                    <input id="loginPass" type="password" placeholder="Password..."></input>
                    <br/>
                    <br/>
                    <button id="loginButton">Login</button>
                </form>
            </div>
        </main>
    </div>
    )
}
