/* eslint-disable */
import Head from 'next/head'
import Image from 'next/image'
import '../styles/Home.module.css'
import Store from '../components/Store'

export default function Home() {
    return (
    <div className="container">
        <Head>
            <title>PixelTs</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.png" />
        </Head>

        <main className="storeMain">
            <Store/>
        </main>
    </div>
    )
}
